### ISSUE TITLE
autoconf error "undefined macro: AM_CONFIG_HEADER"

### ISSUE THREAD

**Issue by ahmedawad1** [rleitner/psplash#2]
I followed these [steps ](http://processors.wiki.ti.com/index.php/Customizing_the_SDK_Splash_Screen) to add my custom splash image till step 1. It looks like **autogen.sh** is obsolete so I use autoconf instead.

 However when I try to execute "$ autoconf" I get the following error:
`configure.ac:3: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:5: error: possibly undefined macro: AM_CONFIG_HEADER
`
Any idea what is this, config.h does not exist in the git repository even! 

Thanks in advance!

**Comment by rleitner** [comment]
Hi,
this repo is here at github only for some kind of historical reasons.
If you face problems please contact the yocto mailinglist at https://lists.yoctoproject.org/listinfo/yocto

https://git.yoctoproject.org/cgit/cgit.cgi/psplash/about/
